version: '3.8'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/horse_racing_forecast:nocopy
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - default
  db:
    image: postgres:13.5
    ports:
      - 5432:5432
    volumes:
      - horse-racing-forecast-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

volumes:
  horse-racing-forecast-data:
    name: psql-data
    driver: local
