version: '3.8'
services:
  db:
    image: postgres:13.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "horse"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/horse_racing_forecast
    ports:
      - "3000:3000"
    depends_on:
      - db
